Forgot to remove G2MotorDriver::
fix `lib/G2MotorDriver/G2MotorDriver.h:40:13: error: expected identifier before ')' token` error due to `G2MotorDriver::` in the method definiton